socketPort: 8091
ESP32URL: "http://192.168.x.x"


# Signal config
signal:
  secretGroup: [x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x]
  myNumber: "+353xxxxxxxx"

# Discord config

